# Generated by Django 2.1.2 on 2018-12-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181221_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='user_details',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='subjects',
            unique_together=set(),
        ),
    ]
