# Generated by Django 2.1.2 on 2018-12-21 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_auto_20181221_2025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject', 'user')},
        ),
    ]
