# Generated by Django 2.1.2 on 2018-12-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20181221_2042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
    ]
