# Generated by Django 2.1.2 on 2019-01-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20181221_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cancel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
