# Generated by Django 2.1.2 on 2019-01-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190102_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='cancel',
        ),
        migrations.AddField(
            model_name='subject',
            name='percent',
            field=models.FloatField(default=0.0),
        ),
    ]
