# Generated by Django 2.1.2 on 2019-01-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190108_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cancel',
            field=models.IntegerField(default=0),
        ),
    ]
