# Generated by Django 2.1.2 on 2019-01-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_subject_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='notes',
            field=models.CharField(default='', max_length=140),
        ),
    ]
