# Generated by Django 2.1.2 on 2019-07-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20190629_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
