# Generated by Django 2.1.2 on 2019-07-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20190713_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semester_no',
            field=models.IntegerField(default=0),
        ),
    ]
