# Generated by Django 2.1.2 on 2019-07-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_semester_semester_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default='sub001', max_length=10),
            preserve_default=False,
        ),
    ]
