# Generated by Django 2.1.2 on 2019-08-05 16:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0018_auto_20190805_2043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('user', 'semester_no', 'start_date', 'end_date')},
        ),
    ]
