# Generated by Django 2.1.2 on 2019-08-05 16:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0019_auto_20190805_2140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('user', 'code', 'semester')},
        ),
    ]
